load("//third_party:defs.bzl", "ml_py_library")

package(default_visibility = ["//src/projects/generative/vamf:__subpackages__"])

ml_py_library(
    name = "betastar_from_vref",
    srcs = ["betastar_from_vref.py"],
    deps = [
        "numpy",
    ],
)
