load("//learning:defs.bzl", "ml_py_library")

package(default_visibility = ["//learning:__subpackages__"])

ml_py_library(
    name = "rank_zero",
    srcs = ["rank_zero.py"],
    deps = [
        "jax",
        "jaxlib",
    ],
)
