load("//third_party:defs.bzl", "ml_py_library")

package(default_visibility = ["//visibility:public"])

ml_py_library(
    name = "mlp",
    srcs = ["mlp.py"],
    deps = [
        "flax",
        "jax",
    ],
)
