load("//third_party:defs.bzl", "ml_py_binary")

package(default_visibility = ["//src/projects/jtrp:__subpackages__"])

ml_py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        "absl-py",
        "//src/utilities:logging",
    ],
)
